[[edge_functions]]
  path = "/kitchen/"
  function = "metadata"

[[redirects]]
  from = "/mix*"
  to = "/kitchen/"
  status = 301

[[redirects]]
  from = "/emojisupply/*"
  to = "https://www.gstatic.com/android/keyboard/emojisupply/:splat"
  status = 200
